### ISSUE TITLE
Are you still working on this plugin? 

### ISSUE THREAD

**Issue by NaturallyAsh** [timoth-y/obsidian-ticktick#1]

**Comment by nulltea** [comment]
Hi @NaturallyAsh, thanks for reaching out! At the moment no, but I mean to continue working on this and [obsidian-hackmd](https://github.com/timoth-y/obsidian-hackmd) soon. 

I've been playing around with [blacksmithgu/obsidian-dataview](https://github.com/blacksmithgu/obsidian-dataview) queries, which is also the engine I'm using in this plugin. Have some ideas to incorporate here.

Currently, the plugin scans all pages where there's a specific tag and uploads it to TickTick collection, one task with subitems per page. Another one I'm thinking of is manual upload or auto upload on exit. Also plan to add auto-upload with configured interval like in [readwiseio/obsidian-readwise](https://github.com/readwiseio/obsidian-readwise).

What are the use cases that would be the most useful to you? Please let me know your ideas.

Also if you're down to get hands dirty with typescript, feel free to fork the repo and make PR! 

In any case, you can expect me to continue working on this repo sometime this fall. In a meantime consider using [blacksmithgu/obsidian-dataview](https://github.com/blacksmithgu/obsidian-dataview) to aggregate tasks into a monthly\weekly page like this:
~~~markdown
```dataview
TASK FROM #meetings AND !"Templates"
WHERE !completed AND file.mtime >= date(2022-08-05) - dur(1 week)
```
~~~

**Comment by NaturallyAsh** [comment]
Thanks for your response! I'd love to see something similar to how the Todoist plugin materializes tasks/projects into Obsidian and allows access to API for querying. But one thing I'd be happy to see from your plugin that the Todoist one lacks is the ability to edit TickTick tasks from within Obsidian. Another thing would if TickTick tasks could work with dataview. So, like I could create a dataview query to fetch the TickTick tasks. 

And I'm not really familiar with typescript, but I think I'll take time to learn it because I would love to contribute in some way. I look forward to seeing the final product of this plugin in (hopefully) a few months!
